# Generated by Django 5.2.6 on 2025-10-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('doi', models.CharField(max_length=255, unique=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('fields_of_study', models.TextField(blank=True, null=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
