# Generated by Django 5.2.6 on 2025-10-09 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_name', models.CharField(max_length=255)),
                ('skill_uri', models.URLField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('embedding_model', models.CharField(default='SBERT-all-mpnet-base-v2', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_skills', to='api.paper')),
            ],
        ),
    ]
